<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="10.0.9" />
        <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.24" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="en_GB.dic"/>
        <Content Include="en_GB.dic">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <None Remove="en_GB.aff"/>
        <Content Include="en_GB.aff">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <None Remove="Data\first-names.csv"/>
        <Content Include="Data\first-names.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <None Update="configs">
            <!-- Exclude the file from analysis -->
            <SonarQubeExclude>true</SonarQubeExclude>
        </None>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WALE.ProcessFile.Core\WALE.ProcessFile.Core.csproj" />
      <ProjectReference Include="..\WALE.ProcessFile.Services.AwsS3\WALE.ProcessFile.Services.AwsS3.csproj" />
      <ProjectReference Include="..\WALE.ProcessFile.Services.AwsSqs\WALE.ProcessFile.Services.AwsSqs.csproj" />
      <ProjectReference Include="..\WALE.ProcessFile.Services.AwsTextract\WALE.ProcessFile.Services.AwsTextract.csproj" />
      <ProjectReference Include="..\WALE.ProcessFile.Services.AzureAiServicesDocumentIntelligence\WALE.ProcessFile.Services.AzureAiServicesDocumentIntelligence.csproj" />
      <ProjectReference Include="..\WALE.ProcessFile.Services.AzureComputerVision\WALE.ProcessFile.Services.AzureComputerVision.csproj" />
      <ProjectReference Include="..\WALE.ProcessFile.Services.AzureOpenAi\WALE.ProcessFile.Services.AzureOpenAi.csproj" />
      <ProjectReference Include="..\WALE.ProcessFile.Services.Cache\WALE.ProcessFile.Services.Cache.csproj" />
      <ProjectReference Include="..\WALE.ProcessFile.Services.Docnet\WALE.ProcessFile.Services.Docnet.csproj" />
      <ProjectReference Include="..\WALE.ProcessFile.Services.Output\WALE.ProcessFile.Services.Output.csproj" />
      <ProjectReference Include="..\WALE.ProcessFile.Services.PdfPig\WALE.ProcessFile.Services.PdfPig.csproj" />
      <ProjectReference Include="..\WALE.ProcessFile.Services.Tesseract\WALE.ProcessFile.Services.Tesseract.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Enums\" />
    </ItemGroup>
</Project>