<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>f7f7f582-eade-4afc-b10f-f07e44e81c04</UserSecretsId>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>WRADI.FileProcess.CmdLine</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.SQS" Version="4.0.2.25" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Microsoft.Extensions.Hosting">
            <HintPath>..\..\..\..\..\usr\local\share\dotnet\shared\Microsoft.AspNetCore.App\9.0.14\Microsoft.Extensions.Hosting.dll</HintPath>
        </Reference>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\WRADI.Services.AbstractionLicence\WRADI.Services.AbstractionLicence.csproj" />
      <ProjectReference Include="..\WRADI.Services.ProcessFile.AbstractionLicence\WRADI.Services.ProcessFile.AbstractionLicence.csproj" />
    </ItemGroup>
</Project>