<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>WRADI.Services.ProcessFile.Orchestrate</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\WALE.ProcessFile.Core\WALE.ProcessFile.Core.csproj" />
      <ProjectReference Include="..\WALE.ProcessFile.Services\WALE.ProcessFile.Services.csproj" />
    </ItemGroup>
</Project>