<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>WALE.ProcessFile.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="PdfPig" Version="0.1.10"/>
        <PackageReference Include="PdfPig.Filters.Jbig2.PdfboxJbig2" Version="0.1.10.2" />
        <PackageReference Include="PdfPig.Rendering.Skia" Version="0.1.10.2" />
        <PackageReference Include="WeCantSpell.Hunspell" Version="5.2.1"/>
    </ItemGroup>
    
</Project>