<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <UserSecretsId>a1ecb904-4dba-4e27-b5f3-18a44a03b85d</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.0" />
        <PackageReference Include="FakeItEasy" Version="9.0.1" />
        <PackageReference Include="Meziantou.Xunit.ParallelTestFramework" Version="2.3.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.9" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
        <PackageReference Include="xunit" Version="2.5.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WRADI.Database.PostgreSQL.AbstractionLicence\WRADI.Database.PostgreSQL.AbstractionLicence.csproj" />
      <ProjectReference Include="..\WRADI.Services.AbstractionLicence\WRADI.Services.AbstractionLicence.csproj" />
      <ProjectReference Include="..\WRADI.Services.Cache.AbstractionLicence\WRADI.Services.Cache.AbstractionLicence.csproj" />
      <ProjectReference Include="..\WRADI.Services.Output.AbstractionLicence\WRADI.Services.Output.AbstractionLicence.csproj" />
    </ItemGroup>

    <Target Name="link_deps" AfterTargets="AfterBuild" Condition=" '$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))' ">
        <Exec Command="ln -sf /opt/homebrew/lib/libleptonica.dylib $(OutDir)x64/libleptonica-1.82.0.dylib" />
        <Exec Command="ln -sf /opt/homebrew/lib/libtesseract.dylib $(OutDir)x64/libtesseract50.dylib" />
    </Target>
</Project>