<Project Sdk="Microsoft.NET.Sdk">
<!-- Note: Add the following package reference to your .csproj file if not already present -->
<!-- <PackageReference Include="EPPlus" Version="7.0.0" /> -->
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\WALE.ProcessFile.Services\WALE.ProcessFile.Services.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Rules\EADigitalTemplateRule.cs" />
      <Compile Remove="Rules\NationRiverTemplateRule.cs" />
      <Compile Remove="Rules\NorthumbrianWaterTemplateRule.cs" />
      <Compile Remove="Rules\YorkshireWaterTemplateRule.cs" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="WALE.ProcessFile.Services">
        <HintPath>..\Tools\WALE.Tools\bin\Debug\net9.0\WALE.ProcessFile.Services.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
