<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>521edc86-8246-47d7-bb4d-e8a96e33265e</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentMigrator" Version="7.2.0" />
      <PackageReference Include="FluentMigrator.Runner" Version="7.2.0" />
      <PackageReference Include="FluentMigrator.Runner.Postgres" Version="7.2.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.2" />
      <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.2" />        
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\WALE.ProcessFile.Database.PostgreSQL\WALE.ProcessFile.Database.PostgreSQL.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
        <DependentUpon>Dockerfile</DependentUpon>
      </Content>
    </ItemGroup>

</Project>
